services:
  - type: web
    name: careersaathi
    runtime: java
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/CareerSaathi-0.0.1-SNAPSHOT.war"
    envVars:
      - key: PORT
        value: 1111
      - key: JAVA_VERSION
        value: 17
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: database_m3tb
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
